/* Aither Weather V28 — AitherBackend account authentication + cloud sync loader. */
const WTWAuth = (() => {
  const BACKEND = window.AITHER_BACKEND_URL || 'https://aither-backend.onrender.com';
  const state = { profile: null, onChange: null };
  const $ = (id) => document.getElementById(id);
  const toast = (msg, error=false) => { let el=$('coreToast'); if(!el){el=document.createElement('div');el.id='coreToast';el.className='toast';document.body.appendChild(el)} el.textContent=msg;el.dataset.error=error?'true':'false';el.classList.add('show');clearTimeout(el._timer);el._timer=setTimeout(()=>el.classList.remove('show'),2800); };

  const dashboardAccountCSS = `
    #localSignInForm{display:grid;gap:12px;margin-top:14px;padding:20px;border:1px solid rgba(255,255,255,.08);border-radius:18px;background:rgba(14,20,36,.78);box-shadow:0 20px 55px rgba(0,0,0,.22);backdrop-filter:blur(20px);-webkit-backdrop-filter:blur(20px)}
    #localSignInForm>label:first-child{margin:0 0 2px;color:#74809e;font-size:10px;font-weight:800;letter-spacing:.14em;text-transform:uppercase}
    #localSignInForm input{width:100%;min-height:46px;padding:11px 13px;border:1px solid rgba(255,255,255,.1);border-radius:10px;background:rgba(255,255,255,.045);color:#eef2ff;outline:none;transition:border-color .18s,box-shadow .18s,background .18s}
    #localSignInForm input::placeholder{color:#8792ad}
    #localSignInForm input:focus{border-color:#7358ff;background:rgba(255,255,255,.06);box-shadow:0 0 0 3px rgba(115,88,255,.16)}
    #localSignInForm .setting-row{margin:2px 0 0;padding:0;border:0}
    #localSignInBtn{width:100%;min-height:46px;border:0;border-radius:10px;background:#7358ff;color:#fff;font-weight:700;box-shadow:0 8px 25px rgba(115,88,255,.2);transition:transform .15s,filter .15s,opacity .15s}
    #localSignInBtn:hover{filter:brightness(1.08)}#localSignInBtn:active{transform:translateY(1px)}#localSignInBtn:disabled{opacity:.6;cursor:wait}
    .signin-local-note{margin:2px 0 0;color:#8792ad;font-size:11px;line-height:1.5}.signin-local-note::before{content:'✓ ';color:#5be49a;font-weight:800}
    .wtw-account-profile{display:grid;gap:12px;padding:20px;border:1px solid rgba(255,255,255,.075);border-radius:18px;background:rgba(14,20,36,.78);box-shadow:0 20px 55px rgba(0,0,0,.18);backdrop-filter:blur(20px);-webkit-backdrop-filter:blur(20px)}
    .wtw-account-profile-head{display:flex;align-items:center;gap:14px}.wtw-account-avatar{width:48px;height:48px;flex:0 0 48px;display:grid;place-items:center;border-radius:14px;background:linear-gradient(135deg,#7358ff,#3ba4ff);color:#fff;font-size:18px;font-weight:800;box-shadow:0 10px 25px rgba(78,107,255,.2)}
    .wtw-account-copy strong,.wtw-account-copy span{display:block}.wtw-account-copy strong{font-size:15px}.wtw-account-copy span{margin-top:3px;color:#8792ad;font-size:12px;overflow-wrap:anywhere}
    .wtw-account-status{display:flex;align-items:center;gap:7px;color:#8ff0bb;font-size:11px;font-weight:650}.wtw-account-status::before{content:'';width:7px;height:7px;border-radius:50%;background:#5be49a;box-shadow:0 0 12px #5be49a}
    .wtw-account-signout{width:100%;min-height:44px;border:1px solid rgba(255,255,255,.1);border-radius:10px;background:rgba(255,255,255,.06);color:#dfe5f7;font-weight:650}.wtw-account-signout:hover{background:rgba(255,255,255,.1)}
    @media(max-width:560px){#localSignInForm,.wtw-account-profile{padding:16px;border-radius:16px}}
  `;
  function installAccountStyle(){if(document.getElementById('wtwDashboardAccountCSS'))return;const s=document.createElement('style');s.id='wtwDashboardAccountCSS';s.textContent=dashboardAccountCSS;document.head.appendChild(s)}
  async function api(path, options={}) { const res=await fetch(`${BACKEND}${path}`,{...options,credentials:'include',headers:{'Content-Type':'application/json',Accept:'application/json',...(options.headers||{})}});let data=null;try{data=await res.json()}catch(_){}if(!res.ok)throw new Error(data?.detail||`HTTP ${res.status}`);return data; }
  function saveProfile(user){state.profile=user||null;try{if(user)localStorage.setItem('wtw-backend-profile',JSON.stringify(user));else localStorage.removeItem('wtw-backend-profile')}catch(_){}if(typeof state.onChange==='function')state.onChange(state.profile)}
  function getProfile(){return state.profile} const isSignedIn=()=>!!state.profile;
  async function refreshSession(silent=true){try{const data=await api('/api/auth/session',{headers:{Accept:'application/json'}});if(data.authenticated&&data.user)saveProfile(data.user);else saveProfile(null);return data}catch(err){if(!silent)toast('Aither Backend is unavailable.',true);return {authenticated:false,user:null}}}
  function setupBackendForm(){installAccountStyle();const form=$('localSignInForm');if(!form||form.dataset.backendReady==='true')return;form.dataset.backendReady='true';form.innerHTML=`<label for="aitherAccountName">AITHER ACCOUNT</label><input id="aitherAccountName" type="text" maxlength="80" autocomplete="name" placeholder="Name"><input id="aitherAccountEmail" type="email" maxlength="320" autocomplete="email" placeholder="Email"><input id="aitherAccountPassword" type="password" minlength="8" maxlength="200" autocomplete="current-password" placeholder="Password (8+ characters)"><div class="setting-row"><button type="submit" id="localSignInBtn" class="btn btn-primary btn-small">Sign in / Create account</button></div><p class="signin-local-note">One account across the Aither ecosystem. Your session is secured by Aither Backend.</p>`;form.addEventListener('submit',async e=>{e.preventDefault();const name=$('aitherAccountName')?.value.trim(),email=$('aitherAccountEmail')?.value.trim(),password=$('aitherAccountPassword')?.value||'';if(!email||password.length<8){toast('Enter an email and a password with at least 8 characters.',true);return}const button=$('localSignInBtn');if(button)button.disabled=true;try{let data;try{data=await api('/api/auth/login',{method:'POST',body:JSON.stringify({email,password})})}catch(loginErr){if(!name)throw loginErr;data=await api('/api/auth/register',{method:'POST',body:JSON.stringify({name,email,password})})}if(!data?.authenticated||!data.user)throw new Error('Account session was not created.');saveProfile(data.user);toast(`Signed in as ${data.user.name}`)}catch(err){toast(err.message||'Account sign-in failed.',true)}finally{if(button)button.disabled=false}})}
  async function signInLocally(rawName,avatar){setupBackendForm();const email=$('aitherAccountEmail')?.value.trim(),password=$('aitherAccountPassword')?.value||'',name=$('aitherAccountName')?.value.trim()||String(rawName||'').trim();if(email&&password){try{let data;try{data=await api('/api/auth/login',{method:'POST',body:JSON.stringify({email,password})})}catch(_){data=await api('/api/auth/register',{method:'POST',body:JSON.stringify({name,email,password})})}saveProfile(data.user);return {ok:true}}catch(err){toast(err.message||'Account sign-in failed.',true);return {ok:false,reason:'error'}}}return {ok:false,reason:'backend-form'}}
  async function signOut(){try{await api('/api/auth/logout',{method:'POST'})}catch(_){}saveProfile(null);toast('Signed out')}
  function isSupportedHere(){return location.protocol==='https:'||location.hostname==='localhost'||location.hostname==='127.0.0.1'} function providers(){return[]} const isConfigured=()=>true;async function renderGoogleButton(){return'unavailable'}async function signInWithMicrosoft(){return{ok:false,reason:'backend-only'}}async function signInWithApple(){return{ok:false,reason:'backend-only'}}function setClientId(){return null}function storedClientId(){return''}function configuredClientId(){return null}function avatars(){return[]}
  function renderAccountProfile(){installAccountStyle();const form=$('localSignInForm');if(!form)return;if(!state.profile){setupBackendForm();return}form.innerHTML=`<div class="wtw-account-profile"><div class="wtw-account-profile-head"><div class="wtw-account-avatar">${String(state.profile.name||state.profile.email||'A').trim().charAt(0).toUpperCase()}</div><div class="wtw-account-copy"><strong>${String(state.profile.name||'Aither Account')}</strong><span>${String(state.profile.email||'')}</span></div></div><div class="wtw-account-status">Connected to Aither Backend</div><button type="button" class="wtw-account-signout" id="wtwAccountSignout">Sign out</button></div>`;$('wtwAccountSignout')?.addEventListener('click',signOut)}
  function exportAccount(){const payload={v:2,profile:state.profile,settings:window.WTWStorage?.getSettings?.()||{},favorites:window.WTWStorage?.getFavorites?.()||[],madeAt:Date.now()};return btoa(unescape(encodeURIComponent(JSON.stringify(payload))))}
  function importAccount(code){try{const p=JSON.parse(decodeURIComponent(escape(atob(String(code||'').trim()))));if(!p||!p.settings)return{ok:false,reason:'unreadable'};window.WTWStorage?.saveSettings?.(p.settings);if(Array.isArray(p.favorites))window.WTWStorage?.saveFavorites?.(p.favorites);return{ok:true,name:p.profile?.name||'',favorites:Array.isArray(p.favorites)?p.favorites.length:0}}catch(_){return{ok:false,reason:'unreadable'}}}
  async function init({onChange}={}){state.onChange=onChange;setupBackendForm();await refreshSession(true);renderAccountProfile();if(typeof onChange==='function')onChange(state.profile)}
  return {init,signOut,getProfile,isSignedIn,isConfigured,isSupportedHere,providers,renderGoogleButton,signInWithMicrosoft,signInWithApple,signInLocally,avatars,exportAccount,importAccount,setClientId,storedClientId,configuredClientId,refreshSession};
})();window.WTWAuth=WTWAuth;const _c=document.createElement('script');_c.src='aither-cloud.js?v=1';document.head.appendChild(_c);